## IP and ports to listen on. Defaults shown.
## Authentication service is locked to localhost as it should only be used by PyTerraBackTyl
BACKEND_SERVICE_IP: '0.0.0.0'
BACKEND_SERVICE_PORT: 2442

USE_AUTHENTICATION_SERVICE: false
AUTHENTICATION_METHOD: ''

BACKEND_PLUGINS_PATH: 'backends'
BACKEND_CLASS: 'pyshelve_backend.PyShelveBackend'
POST_PROCESS_CLASSES: []

LOG_LEVEL: 'DEBUG' # INFO, DEBUG, WARNING, ERROR

##
##  pyshelve_backend.PyShelveBackend configuration
##

# The path to where the python shelf objects should be saved (no trailing slash).
PYSHELVE_DATA_PATH: '/opt/pyterrabacktyl/data'

# The filename for the tfstate shelf objects -- the environment name will be prepended
# e.g. for environment TEST, file name will be TEST_terraform_state
PYSHELVE_DB_FILE_NAME: '_terraform_state'