name: Build and Run Docker Image

on:
  push:
    branches:
      - 'ci'  # Trigger on push to release branches

jobs:
  build_and_run:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Image name
        run: |
          echo DOCKER_IMAGE_NAME=$(echo ${{ github.event.repository.name }} | tr '[A-Z]' '[a-z]') | tee -a $GITHUB_ENV
          echo CODELINE=$(echo ${{ github.ref_name }} | tr '[A-Z]' '[a-z]') | tee -a $GITHUB_ENV
          echo INSTANCE_NAME=${{ github.ref_name }}_InT | tee -a $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:${{ env.CODELINE }}

      - name: Run Docker Container
        run: |
          docker run -d --name ${{ env.INSTANCE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:${{ env.CODELINE }}

      # - name: Clean Up
      #   run: |
      #     docker rm -f my_running_container || true
      #     docker rmi $DOCKER_IMAGE_NAME:$CODELINE || true
