name: Build and Run Docker Image

on:
  push:
    branches:
      - 'ci'  # TODO: Trigger on push to release branches

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - name: echo one
    run: |
      COLS="|One|Two|Three|"
      echo "$COLS" | tee -a $GITHUB_STEP_SUMMARY
      echo "$COLS" | sed -r 's/[^|]/-/g' | tee -a $GITHUB_STEP_SUMMARY
  - name: echo two
    run: |
      echo "|1|2|3|" | tee -a $GITHUB_STEP_SUMMARY
  - name: echo three
    run: |
      echo "|4|5|6|" | tee -a $GITHUB_STEP_SUMMARY
